# Generated by Django 5.1.5 on 2025-02-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=100)),
                ('field2', models.TextField()),
                ('character_name', models.CharField(default='Unknown', max_length=100)),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
